### ISSUE TITLE
Throughput issue with multi-topic subscription

### ISSUE THREAD

**Issue by xkrillex** [zio/zio-kafka#1004] opened 2023-07-28 07:12 UTC
Hi, there seems to be an issue which results in very low througput when subscribing to multiple topics. See reproducer code below. 

This is with zio 2.0.13 and zio-kafka 2.4.1

1. Create a topic `_test_topic1` and `_test_topic2` both with 2 partitions
2. Run `ReproducerProducer` and wait for it to fill up _test_topic1 with 200k messages
3. Run `ReproducerConsumer`.

On my local machine the consumption of those 200k messages takes about 1 min 45 seconds. If I do it over again and removing `_test_topic2` from the Consumer it takes no time at all.

```scala
object ReproducerProducer extends ZIOAppDefault { self =>

  override def run: ZIO[Environment with ZIOAppArgs with Scope, Nothing, Any] = {

    val appLogic = (for {
      key <- ZIO.randomWith(_.nextUUID)
      value <- ZIO.randomWith(_.nextInt)
      _ <- Producer.produce("_test_topic1", key.toString, value.toString, Serde.string, Serde.string)
    } yield ()).repeatN(200000)

    val producerSettings = ProducerSettings(List("localhost:9092"))

    appLogic.provideLayer(ZLayer.scoped(Producer.make(producerSettings))).exitCode

  }

}

object ReproducerConsumer extends ZIOAppDefault { self =>

  override def run: ZIO[Environment with ZIOAppArgs with Scope, Nothing, Any] = {

    val consumerSettings = ConsumerSettings(List("localhost:9092"))
      .withGroupId("test_consumer_group")
      .withCloseTimeout(30000.milliseconds)
      .withPollTimeout(50.milliseconds)
      .withOffsetRetrieval(OffsetRetrieval.Auto(AutoOffsetStrategy.Earliest))
      .withProperties(
        ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG -> "45000",
        ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG -> "30000",
        ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG -> "3000",
        ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG -> "10000",
        ConsumerConfig.FETCH_MIN_BYTES_CONFIG -> "1",
        ConsumerConfig.MAX_POLL_RECORDS_CONFIG -> "500",
        ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG -> "300000",
      )

    val consumer = Consumer
      .partitionedStream(Topics(Set("_test_topic1", "_test_topic2")), Serde.string, Serde.string)
      .flatMapPar(10) {
        case (_, partition) =>
          partition
            .aggregateAsyncWithin(
              ZSink.foldUntil[CommittableRecord[String, String], (OffsetBatch, Chunk[CommittableRecord[String, String]])]((OffsetBatch.empty, Chunk.empty[CommittableRecord[String, String]]), 2048) {
                case ((offsets, records), record) =>
                  (offsets.add(record.offset), records.appended(record))
              },
              Schedule.fixed(5.seconds)
            )
          .mapZIO {
            case (offsets, records) =>
              for {
                _ <- ZIO.logDebug(s"Consumer processing batch of ${records.size}. Committing offset...")
                _ <- offsets.commitOrRetry(Schedule.spaced(100.milliseconds) && Schedule.recurs(10))
                _ <- ZIO.logDebug("Commit done")
              } yield ()
          }
      }
      .provideLayer(ZLayer.scoped(Consumer.make(consumerSettings)))

    val producerSettings = ProducerSettings(List("localhost:9092"))

    consumer
      .runDrain
      .provide(ZLayer.scoped(Producer.make(producerSettings)), LogLayers.layer)
      .exitCode
  }

}

```

**Comment by xkrillex** [comment] 2023-07-28 07:31
Tried changing max.poll.records from 500 to 100 - exactly same amount of time to consume 200k messages. 
Changing it to 10000 - about 35 seconds.

**Comment by erikvanoosten** [comment] 2023-07-29 08:56
For optimal throughput try to increase the poll timeout. E.g. 500ms instead of 50.

xkrillex ***@***.***> schreef op 28 juli 2023 09:31:19 CEST:
>Tried changing max.poll.records from 500 to 100 - exactly same amount of time to consume 200k messages. 
>Changing it to 10000 - about 35 seconds.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/zio/zio-kafka/issues/1004#issuecomment-1655190786
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Erik van Oosten
***@***.***
http://day-to-day-stuff.blogspot.com

**Comment by xkrillex** [comment] 2023-07-31 06:31
Tried that now. Did not have any impact in this scenario. Still took about 1 min 45 seconds.

**Comment by svroonland** [comment] 2023-08-02 10:55
Had a brief look at this, and it looks like a kafka / kafka client issue. I'm seeing a lot of polls where all partitions are unpaused but with 0 records as a result, alternated by periods of getting 500 records. With just 1 topic I see just sequences of 500 records..

Can't say for sure yet that it's not a zio-kafka issue, but perhaps you could try this with another kafka client and see what happens.

**Comment by erikvanoosten** [comment] 2023-08-03 09:54
The code is structured such that processing many partitions causes throughput problems. This is because the commits are done concurrently per partition. The broker gets slow when it has to deal with so many commits. It would be better for each of the streams to produce the committable offsets, merge all the streams and then aggregateAsync those before doing the commits. The end result is that a single commit is active at any time.

I will close this issue but please do re-open it if you think this answer is incorrect!

**Comment by svroonland** [comment] 2023-08-03 10:52
Should be easy to verify that, but I doubt that's the cause here. I will try later this week.

**Comment by xkrillex** [comment] 2023-08-03 11:59
Makes sense to do it like you describe. But in this example I'm not sure if it changes anything since the second topic never receives any messages. Will try when I get the chance.

**Comment by erikvanoosten** [comment] 2023-08-03 13:16
> I'm not sure if it changes anything since the second topic never receives any messages

Hmm, indeed. In that case it shouldn't matter at all. 🤔

**Comment by svroonland** [comment] 2023-08-04 18:10
Made a reproducer here with the commit stage after the `flatMapPar`. I adjusted the producing code somewhat because it took forever to produce 200K records.

https://github.com/zio/zio-kafka/compare/master...fix-1004

To run:
`docker-compose --project-name="zio-kafka" up -d`

In sbt:
* `zioKafka/runMain zio.kafka.ReproducerProducer`
* `zioKafka/runMain zio.kafka.ReproducerConsumer`

Observe the sequence of "Got 500 records" followed by many "Got 0 records", followed by another batch of "Got 500 records", all while all partitions are always  unpaused.

**Comment by xkrillex** [comment] 2023-10-31 18:47
Just to mention: with the release of zio-kafka version 2.6.0 has had an impact of this:

As mentioned above processing of 200k messages took about 1 min 45 seconds previously. With the same setup in version 2.6.0 it dropped to ~57 seconds. For me it seemed to be the same with `tuneForLowLatency` and `tuneForHighThroughput` in this case.

**Comment by erikvanoosten** [comment] 2023-11-01 08:02
> Just to mention: with the release of zio-kafka version 2.6.0 has had an impact of this:
> 
> As mentioned above processing of 200k messages took about 1 min 45 seconds previously. With the same setup in version 2.6.0 it dropped to ~57 seconds. For me it seemed to be the same with `tuneForLowLatency` and `tuneForHighThroughput` in this case.

Great!
It seems you are benefiting from the automatic merging of commits. Since the tuning parameters have no effect, it could be that committing is the bottleneck in your system. To try this out, you could either merge the offsets yourself, or increase max poll timeout further.

**Comment by erikvanoosten** [comment] 2023-11-29 10:48
I think I know why this code performs poorly.

The problem is in this part:
```scala
                _ <- ZIO.logDebug(s"Consumer processing batch of ${records.size}. Committing offset...")
                _ <- offsets.commitOrRetry(Schedule.spaced(100.milliseconds) && Schedule.recurs(10))
```

Commits are (semantically) blocking. Commits take some time because we only get a confirmation at the start of a poll. This happens once every `poll timeout`.

So in effect the program is processing, waiting for commits, processing, waiting for commits, etc.

The solution is to do record processing above the `aggregateAsyncWithin` and committing below it.

**Comment by erikvanoosten** [comment] 2023-11-29 13:14
@svroonland I think that is not sufficient. `mapZIOParUnordered(8)` may pull up to 8 records ahead, that is not a lot considering that we're expecting 200k records to be processed in a few seconds. So this reduces the number of commit waits by a factor of 8, but it has to be reduced by several orders of magnitude.

With `aggregateAsyncWithin` we can aggregate thousands of records and the problem should be gone.

**Comment by svroonland** [comment] 2023-11-29 18:06
I think it pulls batches of up to 2048 offsets or 5 seconds, see https://github.com/zio/zio-kafka/compare/master...fix-1004#diff-9145d96db51be2b905d8841892165b424dbcdbcdb22c0255aefb0b35fed6a24bR73

**Comment by erikvanoosten** [comment] 2023-11-29 19:03
Ow, I see, I missed that part. What happens when the `aggregateAsyncWithin` is moved out to the merged stream?

**Comment by svroonland** [comment] 2024-04-04 18:22
Updated the `fix-1004` branch to the latest zio-kafka version (master). The example now runs in a couple of seconds. Not sure what fixed the issue, there have been several apache kafka upgrades since last zio-kafka version though.

@xkrillex Could you confirm the issue is no longer present with the latest version?

**Comment by xkrillex** [comment] 2024-04-09 06:02
Confirmed! 👍 💯

**Closed** 2024-04-09 06:02 UTC
