### ISSUE TITLE
is Transactional Producer supported in this project?

### ISSUE THREAD

**Issue by cheatmenot** [zio/zio-kafka#123] opened 2020-02-18 10:38 UTC
is Transactional Producer semantics is supported here? if yes, can you give me example? Thanks!

**Comment by iravid** [comment] 2020-02-19 07:34
@cheatmenot Not yet. You can enable producer idempotence by passing `enable.idempotence = true` to the `ProducerSettings`, but transactions are not yet natively supported by the project.

I personally do not use these features, so contributions very welcome.

**Comment by iravid** [comment] 2020-02-19 07:34
Closing as duplicate of #33.

**Closed by iravid** 2020-02-19 07:34 UTC
