### ISSUE TITLE
Runloop crash causes indefinite hanging

### ISSUE THREAD

**Issue by fd8s0** [zio/zio-kafka#977] opened 2023-07-11 14:51 UTC
This happened to me using zio-kafka 2.3.2
The environment is very unstable and at times the connection to zookeeper drops.

If I see in the logs "Error in Runloop", then the consumer keeps running but no messages can ever be consumed.

`Exception in thread "zio-fiber-" zio.kafka.consumer.Consumer$RunloopTimeout$: Timeout in Runloop" location=zio.kafka.consumer.internal.Runloop.run file=Runloop.scala line=469`

Ideally I would expect the consumer to fail in this case.

**Comment by erikvanoosten** [comment] 2023-07-11 17:22
From https://discord.com/channels/629491597070827530/629497941719121960/1128358821602005033:
> I think is because we boot an entire stack of servers in test and they take some time to come up, 4 minutes seems excessive, I bumped it to 10 in my consumers. Once they're up I've never seen this happen before. The entire Kafka cluster would have to go down for it to trigger at runtime I assume?

Okay, this explains the cause. There is a time out in the runloop after it had nothing to do for too long. You can work around this by setting a higher runloopTimeout in the consumer settings.

The runloop timeout is gone once #960 gets merged (might take a while, it seems summer vacation has started).

**Comment by erikvanoosten** [comment] 2023-11-29 10:49
@fd8s0 this problem should be resolved by now. Please re-open if you still have this problem after upgrading to at least zio-kafka 2.7.0.

**Closed by erikvanoosten** 2023-11-29 10:49 UTC
